import type { Metadata } from "next";

// import "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"

// import "http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css"

import "@/styles/dist/css/AdminLTE.min.css"
import "@/styles/dist/css/skins/_all-skins.min.css"
import "@/styles/plugins/iCheck/flat/blue.css"
import "@/styles/plugins/morris/morris.css"
import "@/styles/plugins/jvectormap/jquery-jvectormap-1.2.2.css"
import "@/styles/plugins/datepicker/datepicker3.css"
import "@/styles/plugins/daterangepicker/daterangepicker-bs3.css"
import "@/styles/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css"
import "@/styles/plugins/datatables/dataTables.bootstrap.css"
import "@/styles/bootstrap/css/bootstrap.min.css"
import "@/styles/main.css"



import ImportScript from "@/components/layout/importJs";
import Aside from "@/components/layout/aside";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
            <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
            <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />    

            
        </head>
        <body className="skin-blue">
            <div className="wrapper">
                <Header />
                <Aside />
                {children}
                <Footer />
            </div>
            <ImportScript/>
        </body>
    </html>
    
  );
}


