import type { Metadata } from "next";

import "@/styles/bootstrap/css/bootstrap.min.css"


import "@/styles/dist/css/AdminLTE.min.css"
import "@/styles/dist/css/skins/_all-skins.min.css"
import "@/styles/plugins/iCheck/flat/blue.css"
import "@/styles/plugins/morris/morris.css"
import "@/styles/plugins/jvectormap/jquery-jvectormap-1.2.2.css"
import "@/styles/plugins/datepicker/datepicker3.css"
import "@/styles//plugins/daterangepicker/daterangepicker-bs3.css"


import ImportScript from "@/components/layout/importJs";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    
    <html lang="en">
      
        {children}
    </html>
    
    
    </>
   
  );
}
